kind: Deployment
apiVersion: apps/v1
metadata:
  name: wire
  namespace: kube-system
  labels:
    dce.daocloud.io/app: frpovn
    dce.daocloud.io/component: wire
  annotations: {}
spec:
  replicas: 1
  selector:
    matchLabels:
      dce.daocloud.io/component: wire
  template:
    metadata:
      name: wire
      labels:
        dce.daocloud.io/app: frpovn
        dce.daocloud.io/component: wire
    spec:
      containers:
        - name: wire
          image: 'registry.cn-hangzhou.aliyuncs.com/sourcegarden/docker-wg:v1.0'
          resources:
            requests:
              cpu: '0'
              memory: '0'
          imagePullPolicy: Always
          securityContext:
            privileged: true
          tty: true
      restartPolicy: Always
      dnsPolicy: Default
      securityContext: {}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - dfpdevds2
---
kind: Service
apiVersion: v1
metadata:
  name: wire
  namespace: kube-system
  labels:
    dce.daocloud.io/app: frpovn
  annotations: {}
spec:
  ports:
    - name: wire-8080
      protocol: UDP
      port: 8080
      targetPort: 8080
  selector:
    dce.daocloud.io/app: frpovn
    dce.daocloud.io/component: wire
  type: ClusterIP